# Generated by Django 3.0.7 on 2020-07-04 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_auto_20200703_1520'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_sources',
            field=models.CharField(default='Sources', max_length=2000),
        ),
    ]
