# Generated by Django 3.0.7 on 2020-07-18 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_auto_20200704_1858'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_class',
            field=models.CharField(default='unclassified', max_length=100),
        ),
        migrations.AddField(
            model_name='article',
            name='article_publisher',
            field=models.CharField(default='Name', max_length=100),
        ),
    ]
