# Generated by Django 3.0.7 on 2020-07-18 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20200718_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_sources',
            field=models.CharField(default='Sources', max_length=2000),
        ),
    ]
