# Generated by Django 3.0.7 on 2020-07-20 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20200718_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_brief',
            field=models.CharField(default='brief', max_length=200),
        ),
    ]
